SUBROUTINE      estimation(ALPHA, GRIDX, GRIDY, DELTAX, DELTAY, PHID, PSI, SIGMAXX, SIGMAYY, SIGMAXY, &
	    	CONC, ORIX, ORIY, delXPSI, delX2PSI, delYPSI, delY2PSI, delO2PSI, delOPSI, delSIGMAX, &
		delSIGMAY, DELdotNCX, DELdotNCY, ENTROPY )

 IMPLICIT NONE

integer, parameter :: dp  = kind(1.0D0)
INTEGER*8, INTENT(IN) :: GRIDX, GRIDY, PHID 
REAL*8, INTENT(IN)  :: ALPHA
REAL*8, INTENT(OUT) :: ENTROPY
REAL(DP), PARAMETER :: TWOPI = 6.283185307179586476925286766559005768394
REAL(DP), PARAMETER :: PI    = 3.141592653589793238462643383279502884197
REAL*8,  INTENT(IN) :: DELTAX, DELTAY
INTEGER I, J, A, P
REAL(dp), DIMENSION(GRIDX,GRIDY,PHID), INTENT(IN) :: PSI 
REAL(dp), DIMENSION(GRIDX,GRIDY,PHID), INTENT(OUT):: delXPSI, delX2PSI, delYPSI, delY2PSI, delO2PSI, delOPSI     		
REAL(dp), DIMENSION(GRIDX,GRIDY), INTENT(OUT) :: SIGMAXY, SIGMAXX, SIGMAYY, CONC, ORIX, ORIY &
	, delSIGMAY, delSIGMAX, DELdotNCX, DELdotNCY 
REAL(dp), DIMENSION(GRIDX,GRIDY) ::  delSIGMAX1, delSIGMAX2, delSIGMAY1, delSIGMAY2, SXY
REAL*8  DA, addPSI3, addPSI4, addPSI5   
  													
SIGMAXY=0.0
SIGMAXX=0.0
SIGMAYY=0.0
CONC=0.0
ORIX=0.0
ORIY=0.0
delSIGMAY=0.0
delSIGMAX=0.0
delXPSI=0.0
delX2PSI=0.0
delYPSI=0.0 
delY2PSI=0.0
delO2PSI=0.0
delOPSI=0.0
SXY=0.0				
DO I=1,GRIDX
	DO J=1,GRIDY
		DO A=1,PHID
			IF (A .LT. PHID) THEN 
				DA=(TWOPI)/(PHID-1)                                            ! RECTANGULAR  RULE
				SIGMAXY(I,J) = SIGMAXY(I,J) + (ALPHA/4.0)* ( SIN(4.0*PI*(A-1)/(PHID-1))* PSI(I,J,A) + &
				SIN(4.0*PI*A/(PHID-1))* PSI(I,J,A+1) )* DA
					
				SIGMAXX(I,J) = SIGMAXX(I,J) + 0.5*ALPHA*( (COS(TWOPI*(A-1)/(PHID-1)))**2.0 - 0.5 )* PSI(I,J,A)* DA + &
				0.5*ALPHA*( (COS(TWOPI*A/(PHID-1)))**2.0 - 0.5 )* PSI(I,J,A+1)* DA
					
				SIGMAYY(I,J) = - SIGMAXX(I,J)
				
				CONC(I,J)    = CONC(I,J)    + 0.5 * ( PSI(I,J,A)+PSI(I,J,A+1) )* DA
					
				ORIX(I,J)    = ORIX(I,J) + 0.5*( COS(TWOPI*(A-1)/(PHID-1))*PSI(I,J,A) &
				+COS(TWOPI*A/(PHID-1))*PSI(I,J,A+1) ) * DA
				
				ORIY(I,J)    = ORIY(I,J) + 0.5*( SIN(TWOPI*(A-1)/(PHID-1))*PSI(I,J,A) &
				+SIN(TWOPI*A/(PHID-1))*PSI(I,J,A+1) ) * DA
												
				IF ( (PSI(I,J,A)>0) .AND. (PSI(I,J,A+1)>0) ) THEN
					SXY(I,J) = SXY(I,J) + PI * ( PSI(I,J,A)*LOG(TWOPI*PSI(I,J,A))+PSI(I,J,A+1)*LOG(TWOPI*PSI(I,J,A+1)) ) &
					* DA
				END IF
			END IF
			


			IF ((I .GT. 1) .AND. (I .LT. GRIDX)) THEN
				delXPSI(I,J,A)=(PSI(I+1,J,A)-PSI(I-1,J,A))/(DELTAX+DELTAX)
				delX2PSI(I,J,A)=(PSI(I+1,J,A)- 2.0 *PSI(I,J,A)+PSI(I-1,J,A))/(DELTAX*DELTAX)
			END IF
			IF ((J .GT. 1) .AND. (J .LT. GRIDY)) THEN
				delYPSI(I,J,A)=(PSI(I,J+1,A)-PSI(I,J-1,A))/(DELTAY+DELTAY)
				delY2PSI(I,J,A)=(PSI(I,J+1,A)- 2.0 *PSI(I,J,A)+PSI(I,J-1,A))/(DELTAY*DELTAY)
			END IF
			delXPSI(1,J,A)=(PSI(2,J,A)-PSI(GRIDX,J,A))/(DELTAX+DELTAX)
			delXPSI(GRIDX,J,A)=(PSI(1,J,A)-PSI(GRIDX-1,J,A))/(DELTAX+DELTAX)
			delYPSI(I,1,A)=(PSI(I,2,A)-PSI(I,GRIDY,A))/(DELTAY+DELTAY)
			delYPSI(I,GRIDY,A)=(PSI(I,1,A)-PSI(I,GRIDY-1,A))/(DELTAY+DELTAY)

			delX2PSI(1,J,A)=(PSI(2,J,A)- 2.0* PSI(1,J,A)+PSI(GRIDX,J,A))/(DELTAX*DELTAX)
			delX2PSI(GRIDX,J,A)=(PSI(1,J,A)- 2.0 *PSI(GRIDX,J,A)+PSI(GRIDX-1,J,A))/(DELTAX*DELTAX)
		        delY2PSI(I,1,A)=(PSI(I,2,A)- 2.0 *PSI(I,1,A)+PSI(I,GRIDY,A))/(DELTAY*DELTAY)
			delY2PSI(I,GRIDY,A)=(PSI(I,1,A)- 2.0 *PSI(I,GRIDY,A)+PSI(I,GRIDY-1,A))/(DELTAY*DELTAY)
				 
			IF ((A .GT. 1) .AND. (A .LT. PHID)) THEN
				delOPSI(I,J,A) = (PSI(I,J,A+1) - PSI(I,J,A-1))/((4.0*PI)/(PHID-1))
				delO2PSI(I,J,A)=( PSI(I,J,A+1)- 2.0 * PSI(I,J,A) + PSI(I,J,A-1) )/( ((2.0*PI)/(PHID-1))**2.0 )
			END IF
			delOPSI(I,J,1) = (PSI(I,J,2) - PSI(I,J,PHID))/((4.0*PI)/(PHID-1))
			delOPSI(I,J,PHID) = (PSI(I,J,1) - PSI(I,J,PHID-1))/((4.0*PI)/(PHID-1))
			
			delO2PSI(I,J,1)=(PSI(I,J,2)- 2.0 *PSI(I,J,1)+PSI(I,J,PHID-1))/( ((2.0*PI)/(PHID-1))*((2.0*PI)/(PHID-1)) )
			delO2PSI(I,J,PHID)=(PSI(I,J,2)- 2.0 *PSI(I,J,PHID)+PSI(I,J,PHID-1))/( ((2.0*PI)/(PHID-1))*((2.0*PI)/(PHID-1)) )

		END DO 
		ORIY(I,J)=ORIY(I,J)/CONC(I,J)
		ORIX(I,J)=ORIX(I,J)/CONC(I,J)
	END DO
END DO

addPSI3=SUM(SIGMAXY)/(gridx*gridy)
SIGMAXY=SIGMAXY - addPSI3
!addPSI3=SUM(SIGMAXX)/(gridx*gridy)
!SIGMAXX=SIGMAXX - addPSI3
!SIGMAYY=-SIGMAXX
!addPSI4=SUM(SIGMAYY)/(gridx*gridy)
!SIGMAYY=SIGMAYY - addPSI4
!addPSI5=SUM(SIGMAXX)/(gridx*gridy)
!SIGMAXX=SIGMAXX - addPSI5
				

!DO I=1,(GRIDX)
!	DO J=1,(GRIDY)
		


!		!IF ((I .GT. 1) .AND. (I .LT. GRIDX)) THEN
!		!	delSIGMAX1(I,J)= (SIGMAXX(I+1,J)-SIGMAXX(I-1,J))/(DELTAX+DELTAX) 
!		!END IF
!		!IF ((J .GT. 1) .AND. (J .LT. GRIDY)) THEN
!		!	delSIGMAY1(I,J)= (SIGMAYY(I,J+1)-SIGMAYY(I,J-1))/(DELTAY+DELTAY)
!		!END IF
!		!IF ((J .GT. 1) .AND. (J .LT. GRIDY)) THEN
!		!	delSIGMAX2(I,J)= (SIGMAXY(I,J+1)-SIGMAXY(I,J-1))/(DELTAY+DELTAY)  
!		!END IF
!		!IF ((I .GT. 1) .AND. (I .LT. GRIDX)) THEN
!		!	delSIGMAY2(I,J)= (SIGMAXY(I+1,J)-SIGMAXY(I-1,J))/(DELTAX+DELTAX)
!		!END IF
!		!delSIGMAX1(1,J)     = (SIGMAXX(2,J)-SIGMAXX(GRIDX,J))   /(DELTAX+DELTAX)
!		!delSIGMAX1(GRIDX,J) = (SIGMAXX(1,J)-SIGMAXX(GRIDX-1,J)) /(DELTAX+DELTAX)
!		!delSIGMAX2(I,1)     = (SIGMAXY(I,2)-SIGMAXY(I,GRIDY))   /(DELTAY+DELTAY)
!		!delSIGMAX2(J,GRIDY) = (SIGMAXY(I,1)-SIGMAXY(I,GRIDY-1)) /(DELTAY+DELTAY)
!		!delSIGMAY1(I,1)	    = (SIGMAYY(I,2)-SIGMAYY(I,GRIDY))   /(DELTAY+DELTAY)
!		!delSIGMAY1(I,GRIDY) = (SIGMAYY(I,1)-SIGMAYY(I,GRIDY-1)) /(DELTAY+DELTAY)
!		!delSIGMAY2(1,J)	    = (SIGMAXY(2,J)-SIGMAXY(GRIDX,J))   /(DELTAX+DELTAX)
!		!delSIGMAY2(GRIDX,J) = (SIGMAXY(1,J)-SIGMAXY(GRIDX-1,J)) /(DELTAX+DELTAX)
!
!		!delSIGMAX(I,J)      = delSIGMAX1(I,J) + delSIGMAX2(I,J)
!		!delSIGMAY(I,J)      = delSIGMAY1(I,J) + delSIGMAY2(I,J)
!		ORIY(I,J)=ORIY(I,J)/CONC(I,J)
!		ORIX(I,J)=ORIX(I,J)/CONC(I,J)
!
!	END DO
!END DO

ENTROPY = 0.0
DO I=1,(GRIDX)
	DO J=1,(GRIDY)
		IF ((I .GT. 1) .AND. (I .LT. GRIDX)) THEN
			DELdotNCX(I,J) = (CONC(I+1,J)*ORIX(I+1,J) - CONC(I-1,J)*ORIX(I-1,J))/(2*DELTAX) 
		END IF
		DELdotNCX(1,J)     = (CONC(2,J)*ORIX(2,J) - CONC(GRIDX,J)*ORIX(GRIDX,J))/(2*DELTAX) 
		DELdotNCX(GRIDX,J) = (CONC(1,J)*ORIX(1,J) - CONC(GRIDX-1,J)*ORIX(GRIDX-1,J))/(2*DELTAX)
		IF ((J .GT. 1) .AND. (J .LT. GRIDY)) THEN
			DELdotNCY(I,J) = (CONC(I,J+1)*ORIY(I,J+1) - CONC(I,J-1)*ORIY(I,J-1))/(2*DELTAY)
		END IF
		DELdotNCY(I,1)     = (CONC(I,2)*ORIY(I,2) - CONC(I,GRIDY)*ORIY(I,GRIDY))/(2*DELTAY) 
		DELdotNCY(I,GRIDY) = (CONC(I,1)*ORIY(I,1) - CONC(I,GRIDY-1)*ORIY(I,GRIDY-1))/(2*DELTAY) 

		ENTROPY 	   = ENTROPY + SXY(I,J)*DELTAX*DELTAY 
	END DO
END DO

end subroutine estimation
