SUBROUTINE tauPderivative(ZETA,De,UXF,UYF,GRIDX,GRIDY,DELTAX,DELTAY,delUXX, delUYY, delUYX, delUXY, &
	TAUpXX,TAUpYY,TAUpXY, delTAUpXXx, delTAUpXYx, delTAUpYYx, delTAUpXXy, delTAUpXYy, delTAUpYYy)

IMPLICIT NONE

integer,   parameter :: dp  = kind(1.0D0)
INTEGER*8, INTENT(IN) :: GRIDX, GRIDY
REAL*8,    INTENT(IN) :: DELTAX, DELTAY
REAL*8,	   INTENT(IN) :: ZETA, De
REAL(dp),  DIMENSION(GRIDX,GRIDY), INTENT(IN)  :: UXF, UYF
REAL(dp),  DIMENSION(GRIDX,GRIDY), INTENT(IN)  :: delUXY, delUYX, delUXX, delUYY
Integer I, J
REAL(dp),  DIMENSION(GRIDX,GRIDY), INTENT(IN)  :: TAUpXX, TAUpYY, TAUpXY
REAL(dp),  DIMENSION(GRIDX,GRIDY), INTENT(OUT) :: delTAUpXXx, delTAUpXYx, delTAUpYYx
REAL(dp),  DIMENSION(GRIDX,GRIDY), INTENT(OUT) :: delTAUpXXy, delTAUpXYy, delTAUpYYy

DO I=1,GRIDX
	DO J=1,GRIDY
		IF ((I .GT. 1) .AND. (I .LT. GRIDX)) THEN
			delTAUpXXx(I,J) = ( TAUpXX(I+1,J)-TAUpXX(I-1,J) )/(DELTAX+DELTAX)
			delTAUpXYx(I,J) = ( TAUpXY(I+1,J)-TAUpXY(I-1,J) )/(DELTAX+DELTAX)
			delTAUpYYx(I,J) = ( TAUpYY(I+1,J)-TAUpYY(I-1,J) )/(DELTAX+DELTAX)
		END IF
		delTAUpXYx(1,J)     = ( TAUpXY(2,J)-TAUpXY(GRIDX,J)   )/(DELTAX+DELTAX)
		delTAUpXYx(GRIDX,J) = ( TAUpXY(1,J)-TAUpXY(GRIDX-1,J) )/(DELTAX+DELTAX)
		delTAUpXXx(1,J)     = ( TAUpXX(2,J)-TAUpXX(GRIDX,J)   )/(DELTAX+DELTAX)
 		delTAUpXXx(GRIDX,J) = ( TAUpXX(1,J)-TAUpXX(GRIDX-1,J) )/(DELTAX+DELTAX)
		delTAUpYYx(1,J)     = ( TAUpYY(2,J)-TAUpYY(GRIDX,J)   )/(DELTAX+DELTAX)
		delTAUpYYx(GRIDX,J) = ( TAUpYY(1,J)-TAUpYY(GRIDX-1,J) )/(DELTAX+DELTAX)

		IF ((J .GT. 1) .AND. (J .LT. GRIDY)) THEN
			delTAUpXXy(I,J) = ( TAUpXX(I,J+1)-TAUpXX(I,J-1) )/(DELTAY+DELTAY)
			delTAUpXYy(I,J) = ( TAUpXY(I,J+1)-TAUpXY(I,J-1) )/(DELTAY+DELTAY)
			delTAUpYYy(I,J) = ( TAUpYY(I,J+1)-TAUpYY(I,J-1) )/(DELTAY+DELTAY)
		END IF
		delTAUpXYy(I,1)     = ( TAUpXY(I,2)-TAUpXY(I,GRIDY)   )/(DELTAY+DELTAY)
		delTAUpXYy(I,GRIDY) = ( TAUpXY(I,1)-TAUpXY(I,GRIDY-1) )/(DELTAY+DELTAY)
		delTAUpXXy(I,1)     = ( TAUpXX(I,2)-TAUpXX(I,GRIDY)   )/(DELTAY+DELTAY)
		delTAUpXXy(I,GRIDY) = ( TAUpXX(I,1)-TAUpXX(I,GRIDY-1) )/(DELTAY+DELTAY)
		delTAUpYYy(I,1)     = ( TAUpYY(I,2)-TAUpYY(I,GRIDY)   )/(DELTAY+DELTAY)
		delTAUpYYy(I,GRIDY) = ( TAUpYY(I,1)-TAUpYY(I,GRIDY-1) )/(DELTAY+DELTAY)
	END DO
END DO

END SUBROUTINE tauPderivative
